repos:
-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: pytest tests
        language: system
        pass_filenames: false
        always_run: true
        stages: [merge-commit]
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
        language: system
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        language: system
